### ISSUE TITLE
Create Scandipwa App Bug

### ISSUE THREAD

**Issue by kghori36** [scandipwa/create-scandipwa-app#62]
Failed to compile.
./node_modules/@scandipwa/scandipwa/src/index.js 35:7
Module parse failed: Unexpected token (35:7)
File was processed with these loaders:
 * ./node_modules/@tilework/mosaic-webpack-import-loader/index.js
You may need an additional loader to handle the result of these loaders.
| }
|
> render(<App />, document.getElementById('root'));
|

I am Getting this error when i run npm run start command after installed csa on my machine
Terminal Shows me Above Error

**Comment by rMazeiks** [comment]
Hi, thanks for your report!

I was unable to reproduce the issue you describe. When creating a new app (`npx create-scandipwa-app test-app`), entering the directory (`cd test-app/`) and running the app (`npm run start`), everything works as expected.

Could you please provide additional details?
- Which OS are you using?
- Node and npm version
- Exact steps you took (exact commands)

Perhaps it would also be helpful if you attached your `package-lock.json`

Thank you!

**Comment by kghori36** [comment]
i am using windows 10 enterprise version
node version - 14.17.0
npm version - 6.14.13
cmd : npx create-scandipwa-app my-app

**Comment by kghori36** [comment]
> Hi, thanks for your report!
> 
> I was unable to reproduce the issue you describe. When creating a new app (`npx create-scandipwa-app test-app`), entering the directory (`cd test-app/`) and running the app (`npm run start`), everything works as expected.
> 
> Could you please provide additional details?
> 
> * Which OS are you using?
> * Node and npm version
> * Exact steps you took (exact commands)
> 
> Perhaps it would also be helpful if you attached your `package-lock.json`
> 
> Thank you!

**still it is not working same issue.**

**Comment by Nightliss** [comment]
Hi there,

I'm having the same issue:

Windows 10 Pro 21H1 (Build 19043.1165)
node v14.17.5
npm v6.14.14
yarn v1.22.11

When issuing command `npx create-scandipwa-app my-app` and yarn is installed, then running `yarn start` produces error like in the OP.

Same command but without yarn (so npm is used), then `npm run start` will produce
```console
> scandipwa-scripts start

Error: Cannot find module '@tilework/mosaic-craco'
```
After installing missing package (`npm i -D @tilework/mosaic-craco`) and running `npm run start` produces error like in the OP.

please change extensions
[yarn.lock.txt](https://github.com/scandipwa/create-scandipwa-app/files/7007272/yarn.lock.txt)
[package-lock.json.txt](https://github.com/scandipwa/create-scandipwa-app/files/7007294/package-lock.json.txt)

I have also noticed that yarn.lock is generated even when yarn is not installed.

**Comment by ahmedalmulki** [comment]
I have same problem :
node : 14.17.5
npm : 6.14.14
OS : ubuntu 20

after run npm run build or start i get the following error 

```
Error: Cannot find module '@tilework/mosaic-craco'
Require stack:
- /var/www/test-store/src/localmodule/my-app/node_modules/@scandipwa/service-worker/build-config/lib/workbox-babel-plugin.js
- /var/www/test-store/src/localmodule/my-app/node_modules/@scandipwa/service-worker/build-config/workbox-dev.js
- /var/www/test-store/src/localmodule/my-app/node_modules/@tilework/mosaic-cra-scripts/lib/build-plugins.js
- /var/www/test-store/src/localmodule/my-app/node_modules/@tilework/mosaic-cra-scripts/lib/craco.js
- /var/www/test-store/src/localmodule/my-app/node_modules/@tilework/mosaic-cra-scripts/bin/cra-scripts.js
- /var/www/test-store/src/localmodule/my-app/node_modules/@scandipwa/scandipwa-scripts/bin/scandipwa-scripts.js
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:889:15)
    at Function.Module._load (internal/modules/cjs/loader.js:745:27)
    at Module.require (internal/modules/cjs/loader.js:961:19)
    at require (internal/modules/cjs/helpers.js:92:18)
    at Object.<anonymous> (/var/www/test-store/src/localmodule/my-app/node_modules/@scandipwa/service-worker/build-config/lib/workbox-babel-plugin.js:3:38)
    at Module._compile (internal/modules/cjs/loader.js:1072:14)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1101:10)
    at Module.load (internal/modules/cjs/loader.js:937:32)
    at Function.Module._load (internal/modules/cjs/loader.js:778:12)
    at Module.require (internal/modules/cjs/loader.js:961:19) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [
    '/var/www/test-store/src/localmodule/my-app/node_modules/@scandipwa/service-worker/build-config/lib/workbox-babel-plugin.js',
    '/var/www/test-store/src/localmodule/my-app/node_modules/@scandipwa/service-worker/build-config/workbox-dev.js',
    '/var/www/test-store/src/localmodule/my-app/node_modules/@tilework/mosaic-cra-scripts/lib/build-plugins.js',
    '/var/www/test-store/src/localmodule/my-app/node_modules/@tilework/mosaic-cra-scripts/lib/craco.js',
    '/var/www/test-store/src/localmodule/my-app/node_modules/@tilework/mosaic-cra-scripts/bin/cra-scripts.js',
    '/var/www/test-store/src/localmodule/my-app/node_modules/@scandipwa/scandipwa-scripts/bin/scandipwa-scripts.js'
  ]
}


ERROR!

     Failed to load extension`s @scandipwa/service-worker craco-plugins script.
     Looked in /var/www/test-store/src/localmodule/my-app/node_modules/@scandipwa/service-worker/build-config/workbox-dev.js file.
     See detailed error log above.

```

**Comment by amiyoghoshstar** [comment]
Im also getting the same error

**Comment by ahmedalmulki** [comment]
@amiyoghoshstar  just run npm install @tilework/mosaic-craco or use yarn

**Comment by naumansigma** [comment]
i have not resovled this issue but it has something to do with OS.
on centos 7 i have already configured it it is working fine the same code and same npm and nodejs version are configured on windows it give the op error.
i am still trouble shooting it but looks some path issue on windows.

**Comment by bytepattern** [comment]
getting the same issue on windows 10

**Comment by discostu001** [comment]
> getting the same issue on windows 10
> 
> ./node_modules/@scandipwa/scandipwa/src/index.js 35:7
> Module parse failed: Unexpected token (35:7)
> File was processed with these loaders:
> 
> * ./node_modules/@tilework/mosaic-webpack-import-loader/index.js
>   You may need an additional loader to handle the result of these loaders.
>   | }
>   |
> 
> > render(, document.getElementById('root'));
> > |

Also getting this issue.

**Comment by vikaskamboj321** [comment]
> Failed to compile. ./node_modules/@scandipwa/scandipwa/src/index.js 35:7 Module parse failed: Unexpected token (35:7) File was processed with these loaders:
> 
> * ./node_modules/@tilework/mosaic-webpack-import-loader/index.js
>   You may need an additional loader to handle the result of these loaders.
>   | }
>   |
> 
> > render(, document.getElementById('root'));
> > |
> 
> I am Getting this error when i run npm run start command after installed csa on my machine Terminal Shows me Above Error

getting same error https://prnt.sc/1ve1kmn

**Comment by alex-iordache** [comment]
Same exact issue. Installed successfully on a Ubuntu machine, but on two sepparate windows 10 machines - the exact same error.
It doesn't matter what node version - I've tried everything:
- installed everything with and without administrator rights
- ran it with and without admin rights
- with or without yarn
- from CMD and PowerShell
- on the desktop and also on the root system folder (c:\app)
- Even imported a working project from a MacOS system
Everything results in the exact same error:

./node_modules/@scandipwa/scandipwa/src/index.js 35:7
Module parse failed: Unexpected token (35:7)
File was processed with these loaders:
 * ./node_modules/@tilework/mosaic-webpack-import-loader/index.js
You may need an additional loader to handle the result of these loaders.
| }
|
> render(<App />, document.getElementById('root'));
|

**Comment by amikamboj** [comment]
HI Scandi,
Good Day!

I am also getting the same issue ::

./node_modules/@scandipwa/scandipwa/src/index.js 35:7
Module parse failed: Unexpected token (35:7)
File was processed with these loaders:
 * ./node_modules/@tilework/mosaic-webpack-import-loader/index.js
You may need an additional loader to handle the result of these loaders.
| }
| 
> render(<App />, document.getElementById('root'));
|

Please help us to solve it

Thank you

**Comment by Santheepkumar** [comment]
Same issue. Its windows spesific issue. In my linux machine its working properly.

Failed to compile.

./node_modules/@scandipwa/scandipwa/src/index.js 35:7
Module parse failed: Unexpected token (35:7)
File was processed with these loaders:
 * ./node_modules/@tilework/mosaic-webpack-import-loader/index.js
You may need an additional loader to handle the result of these loaders.
| }
|
> render(<App />, document.getElementById('root'));

**Comment by fjaatheen** [comment]
Hello, 

I have the same issue with windows 10.

Failed to compile
./node_modules/@scandipwa/scandipwa/src/index.js 35:7
Module parse failed: Unexpected token (35:7)
File was processed with these loaders:
 * ./node_modules/@tilework/mosaic-webpack-import-loader/index.js
You may need an additional loader to handle the result of these loaders.
| }
| 
> render(<App />, document.getElementById('root'));
|

**Comment by Mohammed-Elmorsy** [comment]
Same issue always getting this error when running npm start : 

./node_modules/@scandipwa/scandipwa/src/index.js 35:7
Module parse failed: Unexpected token (35:7)
File was processed with these loaders:
 * ./node_modules/@tilework/mosaic-webpack-import-loader/index.js
You may need an additional loader to handle the result of these loaders.
| }
| 
> render(<App />, document.getElementById('root'));
|

OS :  Windows 10.0.19041 N/A Build 19041
Node version : 14.15.5
NPM version : 8.1.1

**Comment by rishigupta121** [comment]
Same issue always getting this error when running npm start :

./node_modules/@scandipwa/scandipwa/src/index.js 35:7
Module parse failed: Unexpected token (35:7)
File was processed with these loaders:

./node_modules/@tilework/mosaic-webpack-import-loader/index.js
You may need an additional loader to handle the result of these loaders.
| }
|
render(, document.getElementById('root'));
|

OS : Windows 10
Node version : 14.15.1
NPM version : 6.14.8

**Comment by Ylmzef** [comment]
Same issue too!

Failed to compile.

```
./node_modules/@scandipwa/scandipwa/src/index.js 28:7
Module parse failed: Unexpected token (28:7)
File was processed with these loaders:
 * ./node_modules/@tilework/mosaic-webpack-import-loader/index.js
You may need an additional loader to handle the result of these loaders.
| }
|
> render(<App />, document.getElementById('root'));
|
```

OS : Windows 10
Node version : 14.15.1
NPM version : 6.14.8

**Comment by Davsiavll** [comment]
Getting same error
```
Failed to compile.

./node_modules/@scandipwa/scandipwa/src/index.js 105:7
Module parse failed: Unexpected token (105:7)
File was processed with these loaders:
 * ./node_modules/@tilework/mosaic-webpack-import-loader/index.js
You may need an additional loader to handle the result of these loaders.
| }
| 
> render(<App />, document.getElementById('root'));
|
```
OS: Ubuntu 20.04
Node: v14.18.2
npm: 6.14.15
Any help at all would be appreciable

**Comment by hardik38** [comment]
Getting same error:
`Failed to compile.

./node_modules/@scandipwa/scandipwa/src/index.js 29:16
Module parse failed: Unexpected token (29:16)
File was processed with these loaders:
 * ./node_modules/@tilework/mosaic-webpack-import-loader/index.js
You may need an additional loader to handle the result of these loaders.
| }
|
> ReactDOM.render(<App />, document.getElementById('root'));
|
`
OS: WIndows 10
Node: v14.18.0
npm: 8.3.0
Can anyone fix this issue.

#scandipwa

**Comment by hardik38** [comment]
Getting same error:
![node-error](https://user-images.githubusercontent.com/98799207/153846546-4b6c3092-d16a-43fa-a0f5-0ba85c2028d0.PNG)

OS: WIndows 10
Node: v14.18.0
npm: 8.3.0
Can anyone fix this issue.

#scandipwa

**Comment by rudracomputech** [comment]
Hi I am also getting same error please help solve

/var/www/websites/my-first-ap> npm start
Failed to compile.
<pre>
./node_modules/@scandipwa/scandipwa/src/index.js 28:7
Module parse failed: Unexpected token (28:7)
File was processed with these loaders:
 * ./node_modules/@tilework/mosaic-webpack-import-loader/index.js
You may need an additional loader to handle the result of these loaders.
| }
|
> render(<App />, document.getElementById('root'));
|

**Comment by luluhoc** [comment]
I'm getting the same error

**Comment by louis8663** [comment]
> I'm getting the same error

Hi Do you have any solution for this?

**Comment by louis8663** [comment]
Hi anyone solve this issue? can help please!!! NEED HELP from someone is kind.

**Comment by aamirxia** [comment]
Failed to compile.

./node_modules/@scandipwa/scandipwa/src/index.js 28:7
Module parse failed: Unexpected token (28:7)
File was processed with these loaders:
 * ./node_modules/@tilework/mosaic-webpack-import-loader/index.js
You may need an additional loader to handle the result of these loaders.
| }
|
> render(<App />, document.getElementById('root'));

STILL NO ONE IS ABLE TO RESOLVE THIS ISSUE ?

**Comment by thechiefishere** [comment]
Follow this link https://github.com/scandipwa/scandipwa/issues/3299.
